### ISSUE TITLE
Footswitch to parameter assignment issue

### ISSUE THREAD

**Issue by geraldmwangi** [moddevices/mod-duo-issues#11]
Steps to bug:
1. New pedalboard
2. Drag in any fx, call it fx1
3. Go to properties of fx1, to on/off actuator assignment
4. In actuator both footswitch1& footswitch2 are available
5. Select footswitch1 and save=> actuator assignment menu disappears
6. click again on on/off actuator assignment
7. Select footswitch2 and save=> only after 2 hits on save actuator assignment menu disappears
8. Go out of properties of fx1 to pedalboard
9. Drag in any other fx (call fx2)
10. Go to properties of fx2-> on/off actuator assignment
11. Footswitch1 should be available, but it is not, only Midilearn is.
12. Back to properties of fx1, on/off actuator assignment: Both footswitches are available
13. Delete fx1 then the footswitches become available for fx2!
14. This bug does not impede the function of the footswich once it is assigned,
      when selecting footswitch2 in step 7, footswitch1 get properly deassigned and footswitch2 works
      as expected

**Comment by geraldmwangi** [comment]
One more note: The same bug occures when fx1 has two ore more footswitch assignable parameters.
If parameter was first set to footswitch1 then to footswitch2, then none are available for the other  footswitch assignable parameters.

**Comment by falkTX** [comment]
I thought I had this fixed already.
It's back again I guess, to be fixed soon.

**Comment by falkTX** [comment]
fixed in the latest mod-ui code.
next MOD update will contain the fix.
