### ISSUE TITLE
On/Off switch Gui issue

### ISSUE THREAD

**Issue by geraldmwangi** [moddevices/mod-duo-issues#14]
There's an issue with the gui when the on/off switch of any fx is mapped to a midi cc.
Steps to reproduce:
New pedalboard:
1) drag in instance of any plugin
2) In the settings of the plugin midilearn the on/off switch (say chan 2 cc 83)
3) Expected behaviour: when cc 83 emits a value >64 gui should switch to 'on', plugin should be in effect
4) Current behaviour:  when cc 83 emits a value >64 gui  switches to 'off', but plugin  is actually on
5) when cc 83 emits a value<64 gui switches to 'on', but plugin is off!
6) When on/off switch is not mapped to any midi cc, but manipulated through gui it act as expected:
    switch 'on'=> plugin active, switch 'off'=> plugin inactive.

So this issue is purely Gui related

**Comment by falkTX** [comment]
You got it backwards :)

Note that you're addressing the _bypass_ parameter.
When bypass is on, sound is off.
When bypass is off, sound is on.

So when your midi controller sends a value >= 64, the bypass gets enabled which means it's now _bypassing audio_.
I know this can be pretty confusing...

our hw controller has a special addressing mode for bypass, which mimics the GUI and puts a light on when processing (bypass off), and turns off the light when not processing (bypass on).

perhaps this should be reversed for midi-cc.
but then you'll see the bypass parameter being on for < 64 values, and being off for >= 64.

both cases are confusing... :S

**Comment by geraldmwangi** [comment]
It's only about the GUI. So just to clarify:
a) Toggle switch 'on' = Bypass 'on'? 
or b) Toggle switch 'on'=  Bypass 'off'?

For me b) makes sense.
Anyway whatever definition a) or b) one takes:
Steps 4) and 6) are inconsistent.
If definition a) is true then step 4) is correct and 6) incorrect
If definition b) is true then step 6) is correct and 4) incorrect

**Comment by falkTX** [comment]
When the plugin modgui/icon has its light on, it means bypass is off. The plugin is processing.

the relevant thing here is if we want to map the _bypass_ or the _processing_ state.
I agree with you that mapping bypass should work in a way so that >=64 value means on, even though the logic is inverted for bypass.

I don't want to complicate things here.
I'll make the change so that midi bypass addressings on mod-host will revert the value.
value <64 => processing off, bypass on
value >= 64 => processing on, bypass off.

does that sound good?

**Comment by geraldmwangi** [comment]
great!

**Comment by falkTX** [comment]
The logic of the audio backend was not matching the GUI stuff.
Fixed in https://github.com/moddevices/mod-host/commit/8c03fcbd1f0ea793497642cce44a4b1bd2f59683, thanks for spotting.

PS: Also now >=64 will mean on/processing.
