### ISSUE TITLE
Midi plugins receive no note-off when toggled off

### ISSUE THREAD

**Issue by geraldmwangi** [moddevices/mod-duo-issues#15]
Steps to reproduce:
1) instantiate a generator (say amsynth) and connect it to a usb hardware midi controller 
2) Send a Note-On event (say C1) and hold the key
3) Toggle the on/off switch of amsynth to off 
4) Release C1
5) Toggle amsynth to 'on'=> The note C1 is still playing
6) When toggling amsynth to 'off' all notes should receive a note-off event?

**Comment by falkTX** [comment]
implemented in mod-host, coming in the next update.
(it will send MIDI all-notes/sound-off when bypassing a plugin)

**Comment by falkTX** [comment]
mod update 0.12.1 is out, which includes a fix for this.
