### ISSUE TITLE
xruns on mod-duo

### ISSUE THREAD

**Issue by fps** [moddevices/mod-duo-issues#2]
The MOD duo works awesomely but sadly there are quite a few XRUNS which are audible, too..

**Comment by falkTX** [comment]
FYI the sporadic xruns have been fixed now.
I left my MOD on all night, and it had _zero_ xruns when I woke up. :)

I don't want to close this bug with just my experience though.
I'll let you know when there's an update you can install.

**Comment by danieldickison** [comment]
I see the number of xrun fluctuate quite a bit while using the browser ui, and I have a newbie question: what is xrun?

**Comment by harryhaaren** [comment]
Hi @danieldickison - an xrun is a "glitch" in audio output, the "x" represents either over or under run. In the case of most PC audio applications, it means the system was too slow to deliver the audio to the output. Sometimes xruns are very bad (glitchy noises) sometimes they're not audible at all.

**Comment by fps** [comment]
Any news on this? It's a real showstopper :(

**Comment by falkTX** [comment]
Fixed on v0.15.0

**Comment by harryhaaren** [comment]
Great - totally hyped to get upgraded (once I get back in the same country as my DUO!)

**Comment by fps** [comment]
confirmed, running since two days and 0 xruns :)
