### ISSUE TITLE
Midi cc on/off switch from traditional midi input lost when pedalboard saved/reloaded

### ISSUE THREAD

**Issue by geraldmwangi** [moddevices/mod-duo-issues#20]
Steps to reproduce:
1) Connect midi (foot-)switch to midi in
2) Create new pedalboard (pb)
3) drag in _one_ new plugin
4) midi learn on/off switch (say midi cc1, chan 1)
5) on/off switch works (cc<64 ->on, cc>64->off)
6) Save pb under name MIDI FOOTSW
7) Create new pb, drag in plugin and save it under another name
8) Reload pb MIDI FOOTSW
9) on/off switch is no longer mapped to cc1, chan1. It's not mapped at all

**Comment by geraldmwangi** [comment]
one more point i forgot:
10) Actuator of on/off switch in plugin in pb MIDI FOOTSW shows 'None'

**Comment by falkTX** [comment]
please ssh into the machine and you'll see the pedalboards saved in /root/.pedalboards/
paste here the contents of that pedalboard please.

**Comment by geraldmwangi** [comment]
adressings.json:
`{"/hmi/knob2": [], "/hmi/knob1": [], "/hmi/footswitch2": [], "/hmi/footswitch1": []}`

manifest.ttl:
`@prefix ingen: http://drobilla.net/ns/ingen# .
@prefix lv2:   http://lv2plug.in/ns/lv2core# .
@prefix pedal: http://moddevices.com/ns/modpedal# .
@prefix rdfs:  http://www.w3.org/2000/01/rdf-schema# .

<midi_footsw.ttl>
    lv2:prototype ingen:GraphPrototype ;
    a lv2:Plugin ,
        ingen:Graph ,
        pedal:Pedalboard ;
    rdfs:seeAlso <midi_footsw.ttl> .`

midi_footsw.ttl:
`@prefix atom:  http://lv2plug.in/ns/ext/atom# .
@prefix doap:  http://usefulinc.com/ns/doap# .
@prefix ingen: http://drobilla.net/ns/ingen# .
@prefix lv2:   http://lv2plug.in/ns/lv2core# .
@prefix midi:  http://lv2plug.in/ns/ext/midi# .
@prefix pedal: http://moddevices.com/ns/modpedal# .
@prefix rdfs:  http://www.w3.org/2000/01/rdf-schema# .

<sequencer_16>
    ingen:canvasX 1016.5 ;
    ingen:canvasY 294.5 ;
    ingen:enabled true ;
    ingen:polyphonic false ;
    lv2:microVersion 0 ;
    lv2:minorVersion 0 ;
    lv2:port <sequencer_16/steps> ,
             <sequencer_16/reset> ,
             <sequencer_16/closed_val> ,
             <sequencer_16/val00> ,
             <sequencer_16/val01> ,
             <sequencer_16/val02> ,
             <sequencer_16/val03> ,
             <sequencer_16/val04> ,
             <sequencer_16/val05> ,
             <sequencer_16/val06> ,
             <sequencer_16/val07> ,
             <sequencer_16/val08> ,
             <sequencer_16/val09> ,
             <sequencer_16/val10> ,
             <sequencer_16/val11> ,
             <sequencer_16/val12> ,
             <sequencer_16/val13> ,
             <sequencer_16/val14> ,
             <sequencer_16/val15> ,
             <sequencer_16/gate> ,
             <sequencer_16/trigger> ,
             <sequencer_16/out> ;
    lv2:prototype http://drobilla.net/plugins/blop/sequencer_16 ;
    pedal:preset <> ;
    a ingen:Block .

<sequencer_16/gate>
    a lv2:CVPort ,
        lv2:InputPort .

<sequencer_16/trigger>
    a lv2:CVPort ,
        lv2:InputPort .

<sequencer_16/out>
    a lv2:CVPort ,
        lv2:OutputPort .

<sequencer_16/val08>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val09>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val14>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val02>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val03>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val00>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val01>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val06>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val07>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val04>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val05>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val12>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/steps>
    ingen:value 16.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/:bypass>
    ingen:value 0.000000 ;
    midi:binding [
        midi:channel 0 ;
        midi:controllerNumber 1 ;
        a midi:Controller ;
    ] ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/closed_val>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val11>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val13>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/reset>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val15>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<sequencer_16/val10>
    ingen:value 0.000000 ;
    a lv2:ControlPort ,
        lv2:InputPort .

<control_in>
    atom:bufferType atom:Sequence ;
    lv2:index 0 ;
    lv2:name "Control In" ;
    lv2:portProperty lv2:connectionOptional ;
    lv2:symbol "control_in" ;
    http://lv2plug.in/ns/ext/resize-port#minimumSize 4096 ;
    a atom:AtomPort ,
        lv2:InputPort .

<control_out>
    atom:bufferType atom:Sequence ;
    lv2:index 1 ;
    lv2:name "Control Out" ;
    lv2:portProperty lv2:connectionOptional ;
    lv2:symbol "control_out" ;
    http://lv2plug.in/ns/ext/resize-port#minimumSize 4096 ;
    a atom:AtomPort ,
        lv2:OutputPort .

<capture_1>
    lv2:index 2 ;
    lv2:name "Capture 1" ;
    lv2:portProperty lv2:connectionOptional ;
    lv2:symbol "capture_1" ;
    a lv2:AudioPort ,
        lv2:InputPort .

<capture_2>
    lv2:index 3 ;
    lv2:name "Capture 2" ;
    lv2:portProperty lv2:connectionOptional ;
    lv2:symbol "capture_2" ;
    a lv2:AudioPort ,
        lv2:InputPort .

<playback_1>
    lv2:index 4 ;
    lv2:name "Playback 1" ;
    lv2:portProperty lv2:connectionOptional ;
    lv2:symbol "playback_1" ;
    a lv2:AudioPort ,
        lv2:OutputPort .

<playback_2>
    lv2:index 5 ;
    lv2:name "Playback 2" ;
    lv2:portProperty lv2:connectionOptional ;
    lv2:symbol "playback_2" ;
    a lv2:AudioPort ,
        lv2:OutputPort .

<serial_midi_in>
    atom:bufferType atom:Sequence ;
    atom:supports midi:MidiEvent ;
    lv2:index 6 ;
    lv2:name "Serial MIDI In" ;
    lv2:portProperty lv2:connectionOptional ;
    lv2:symbol "serial_midi_in" ;
    http://lv2plug.in/ns/ext/resize-port#minimumSize 4096 ;
    a atom:AtomPort ,
        lv2:InputPort .

<serial_midi_out>
    atom:bufferType atom:Sequence ;
    atom:supports midi:MidiEvent ;
    lv2:index 7 ;
    lv2:name "Serial MIDI In" ;
    lv2:portProperty lv2:connectionOptional ;
    lv2:symbol "serial_midi_out" ;
    http://lv2plug.in/ns/ext/resize-port#minimumSize 4096 ;
    a atom:AtomPort ,
        lv2:OutputPort .

<>
    doap:name "midi footsw" ;
    pedal:width 3070 ;
    pedal:height 1450 ;
    pedal:addressings <addressings.json> ;
    pedal:screenshot <screenshot.png> ;
    pedal:thumbnail <thumbnail.png> ;
    ingen:polyphony 1 ;
    ingen:block <sequencer_16> ;
    lv2:port <control_in> ,
             <control_out> ,
             <serial_midi_in> ,
             <serial_midi_out> ,
             <capture_1> ,
             <capture_2> ,
             <playback_1> ,
             <playback_2> ;
    lv2:extensionData http://lv2plug.in/ns/ext/state#interface ;
    a lv2:Plugin ,
        ingen:Graph ,
        pedal:Pedalboard .`

**Comment by falkTX** [comment]
please repaste them with code tags between them, or pastebin them somewhere else.
the data is lost due to github formatting text.

**Comment by falkTX** [comment]
After some investigation I found out this is only an issue for bypass.
Normal plugin controls work fine with MIDI-CC.

**Comment by geraldmwangi** [comment]
Ok, I'll recheck that later on.
Gerald / JimsonDrift

**Comment by falkTX** [comment]
this has been fixed in the latest mod-ui code.
the next MOD update will bring the fix.

**Comment by falkTX** [comment]
mod update 0.12.1 is out, which includes a fix for this.
