### ISSUE TITLE
clicking on a knob (in the webgui) increments the value

### ISSUE THREAD

**Issue by thijz** [moddevices/mod-duo-issues#23]
by simply clicking on a knob in the webgui the knob value goes up in small increments each time you click

**Comment by falkTX** [comment]
yep, that's a proud feature of ours.
working as intended.

**Comment by thijz** [comment]
hmmm ... dont know if i like this 100%, but i can see some benefit in it, provided that : 
- it is documented (maybe a hint can appear when you hover over the knob)
- there is a similar way to decrement the value (how about shift-click ?) > if this only works in 1 way it's rather useless IMHO
