### ISSUE TITLE
midi port is duplicated on each pedal board load

### ISSUE THREAD

**Issue by thijz** [moddevices/mod-duo-issues#25]
hardware setup: AKAI mpk mini connected to mod via USB
pedalboard setup: midi input from AKAI is connected to AMsynth

each time i open this pedalboard (from the pedalboards library) an extra midi input pops up and a connection is added from a midi input that seems to be outside of the canvas to AMsynth
(the same goes for the midi output to the MPK)

![image](https://cloud.githubusercontent.com/assets/1384210/14157052/b6bc9c5c-f6c9-11e5-9382-2d5e471d1fe6.png)

when i hover above any of the new midi inputs it shows 'mpk mini'

simply closing the browser tab (using chrome Version 49.0.2623.110 (64-bit) on ubuntu 12.04 64bit) and opening the MOD gui in a new tab fixes this issue

system version : 3b9db27
contr ver : 082a844

**Comment by falkTX** [comment]
yesterday I noticed this myself too.
hopefully will be fixed in the next update.

**Comment by falkTX** [comment]
fixed in mod-ui code.
next mod update will bring the fix.

**Comment by falkTX** [comment]
mod update 0.12.1 is out, which includes a fix for this.
