### ISSUE TITLE
renaming assignment label

### ISSUE THREAD

**Issue by ichier** [moddevices/mod-duo-issues#26]
- assign function to footswitch/knob, save
- edit, change label, save
- change is lost

**Comment by falkTX** [comment]
my fault.
when I added midi learn I had to make sure pressing 'ok' on the addressing dialog did nothing if the addressing was left unchanged.
forgot about this case of renaming a label.

we're making a new release right now and this was not included, but it will be on the one after it.

**Comment by ichier** [comment]
i guess you realized, that the other stuff (sensitivity, range) is also affected, right? if not, hereby reported ;)

**Comment by falkTX** [comment]
yes, it's not just the label that you can modify when re-addressing.
should be easy to fix, coming soon.

**Comment by falkTX** [comment]
Fixed in 0.14.0 release.

**Comment by falkTX** [comment]
Fixed in 0.14.0 release.
