### ISSUE TITLE
Clicking on the title of a pedalboard does not load it

### ISSUE THREAD

**Issue by fps** [moddevices/mod-duo-issues#3]
One needs to click on the pedalboard itself (i.e. the empty box of woody pedalboard background). It took me waaaay to long to figure this out which probably tells more about me than the interface ;)

**Comment by falkTX** [comment]
small note: that "empty" pedalboard background should not be empty at all.
we had it working before (it shows a spinning wheel and then a screenshot), but the designers changed something that broke it :(

in any case, clicking on the title to load the pedalboard is a good idea, we'll implement that soon.

**Comment by boomshop** [comment]
mod-ui master 5500a1c
