### ISSUE TITLE
Version number not exposed on the unit or assembler

### ISSUE THREAD

**Issue by jonobacon** [moddevices/mod-duo-issues#35]
## Bug or Enhancement

Enhancement.
## Description

Currently the upgrade process requires knowledge of which version of the firmware is installed on the unit. There is no current way to discover this.
## Expected/suggested solution

Ideally this will be exposed in the settings, likely under _Info_.
## Would you be willing or able to help resolve this issue?

No.

**Comment by falkTX** [comment]
version is now displayed in info->versions menu in the controller, starting with v0.13.0.
