### ISSUE TITLE
Params Frequency default > maximum

### ISSUE THREAD

**Issue by SrMouraSilva** [moddevices/mod-duo-issues#37]
Example:
In http://api.moddevices.com/lv2/plugins/56c4bc93770cb318f9cd4112/
default (440.0) > maximum (1.0)

``` json
{"designation": "", "index": 6, "name": "Frequency", "properties": ["logarithmic", "sampleRate"], "rangeSteps": null, "ranges": {"default": 440.0, "maximum": 1.0, "minimum": 9.999999974752427e-07}, "scalePoints": [], "shortName": "Frequency", "symbol": "freq", "units": {"label": "hertz", "render": "%f Hz", "symbol": "Hz"}}
```

Errors:

| Effect name | Parameter name | Min | max | default |
| --- | --- | --- | --- | --- |
| Moog Low-Pass Filter 4 | Frequency | 9.99999997475243e-007 | 1 | 440 |
| Moog Low-Pass Filter 3 | Frequency | 9.99999997475243e-007 | 1 | 440 |
| Moog Low-Pass Filter 2 | Frequency | 9.99999997475243e-007 | 1 | 440 |
| Moog Low-Pass Filter 1 | Frequency | 9.99999997475243e-007 | 1 | 440 |
| Moog High-Pass Filter 1 | Frequency | 9.99999997475243e-007 | 1 | 440 |
| Triangle | Frequency | 9.99999997475243e-007 | 0.5 | 440 |
| Square | Frequency | 9.99999997475243e-007 | 0.5 | 440 |
| Sawtooth | Frequency | 9.99999997475243e-007 | 0.5 | 440 |
| Tracker | High Attack Rate | 9.99999974737875e-006 | 0.5 | 100 |
| Tracker | High Decay Rate | 9.99999974737875e-006 | 0.5 | 100 |
| Tracker | Low Attack Rate | 9.99999974737875e-006 | 0.5 | 100 |
| Tracker | Low Decay Rate | 9.99999974737875e-006 | 0.5 | 100 |
| Random Wave | Frequency | 9.99999997475243e-007 | 0.5 | 440 |
| Pulse | Frequency | 9.99999997475243e-007 | 0.5 | 440 |

**Comment by falkTX** [comment]
You need to read the documentation: http://lv2plug.in/ns/lv2core/#sampleRate

> bounds specified should be interpreted as multiples of the sample rate

440 < 1*48000, which is obviously correct.

**Comment by SrMouraSilva** [comment]
I'm sorry, but... the default should be 440/48000?

**Comment by falkTX** [comment]
the default is not multiplied by sampleRate, only the bounds (minimum and maximum)

**Comment by SrMouraSilva** [comment]
Ah, ok. Sorry
