### ISSUE TITLE
System upgrade instructions to "unplug" might be confusing

### ISSUE THREAD

**Issue by danieldickison** [moddevices/mod-duo-issues#38]
Minor feedback on wording: when in system upgrade mode, the left LCD says "copy file, eject and unplug". I think the "unplug" here might lead some users to unplug the power rather than the USB cable. Perhaps spelling out "unplug USB" would be better, or ideally make it work without disconnecting the cable (or over wifi!)

**Comment by fps** [comment]
just for the record: i never unplugged the USB cable and it worked just fine every time :)

**Comment by falkTX** [comment]
the unplug is only needed in Mac OS.
it's ok to remove it while updating anyway, so the message is there just in case the user has Mac OS.

**Comment by odurc** [comment]
From next release all upgrades will be triggered via user interface then this message will not be relevant to regular users.
