### ISSUE TITLE
Mod Duo will no longer connect to Windows 7 or Windows 10 PC

### ISSUE THREAD

**Issue by basslayer** [moddevices/mod-duo-issues#41]
My mod duo has had trouble connecting to either of my computers. It connected after I followed the update instructions and I made three pedal boards. Since I made those boards, it will not connect to either of my Windows PCs.

**Comment by falkTX** [comment]
which mod version are you using?

(should be visible in the left screen menu, under info -> versions.
press and hold left knob to open the menu)

**Comment by basslayer** [comment]
it doesn't seem to have a version listed; release, restore,system and controller are all blank after the colon. i did the latest update, but i can try installing it again.

**Comment by falkTX** [comment]
yes, please reinstall the latest update.
something went wrong with the upgrade process on your last update.. hmmm...

**Comment by basslayer** [comment]
it has been sitting in "starting upgrade, please wait" for the last 2 hours.

**Comment by basslayer** [comment]
coming to the one hour mark on this new attempt that i started right after i last posted.

**Comment by falkTX** [comment]
yeah, then something definitely went wrong with the last update.
luckily we are prepared for this.

do this:
1. unplug the mod power supply
2. hold the left knob and footswitch down
3. connect the mod power supply
4. wait 5 seconds while still holding the buttons down

this will start the update mode for you.

**Comment by basslayer** [comment]
i followed your instructions and i was able to enter upgrade mode. i did the update and checked the version, but release, restore,system and controller are all still blank. it is still not recognized by any computers.

**Comment by basslayer** [comment]
i realized that the mod duo shows up as a recognized device only if i plug it in to the power while its connected to the computer. it still has no listed version and the ip address used to communicate with the mod duo is still displaying like a broken link, but this is the only way it is recognized by my computer  outside of as a mass storage device when in upgrade mode.

**Comment by falkTX** [comment]
You're using the 0.13 version right?

Please try the new (in-testing) 0.14 version.
link: http://download.moddevices.com/releases/modduo/modduo-v0.14.0.tar

thanks

**Comment by basslayer** [comment]
i tried the new version. the release, restore,system and controller remain blank. there is a new option "device" that has a blank entry for serial number. it still remains unrecognized by pcs unless i power it up while connected to the usb, and even then it is still not allowing me to access 192.168.51.1 to make plugins or boards.

**Comment by falkTX** [comment]
just to confirm, when booted your mod shows the "mod duo" on the right display and then it changes to "knob #2", right?

**Comment by basslayer** [comment]
yes. after ~ 26 seconds the right display goes from the typeface "Mod Duo" logo while the left has the symbol logo to the right saying "knob #2" with a dotted line followed by "foot #2" with corresponding information in the left screen for knob and foot #1.

**Comment by basslayer** [comment]
i decided to take some pictures of the mod duo screens since that was easier than typing. i still can't access the pedal from the ip address, but the screens under setting changed a few times. i first cycled through and saw the blank listing under version. the following pictures are the sequence of the screens changing:

![k1gxrws - imgur](https://cloud.githubusercontent.com/assets/13802322/15692697/8c90309e-2755-11e6-819d-0d5f5c31c8bd.jpg)

this was new. before today, everything listed here was unknown.

![htxxlxa - imgur](https://cloud.githubusercontent.com/assets/13802322/15692723/ac98d92c-2755-11e6-96c6-2c2b6fab08aa.jpg)

this was also new. before today, everything here was blank.

![erqr8ap - imgur](https://cloud.githubusercontent.com/assets/13802322/15692745/d8a8a286-2755-11e6-9cad-fb2065d00a6b.jpg)

this was also new. the serial number was blank prior today. 

![8whwt3n - imgur](https://cloud.githubusercontent.com/assets/13802322/15692777/01d683da-2756-11e6-8fdf-f270074ea8d6.jpg)

i tried to access the pedal through the ip address and i was still unable to do so. i tried to see if the menus changed from what i saw this is what showed up.

![lqpcpr9 - imgur](https://cloud.githubusercontent.com/assets/13802322/15692818/4e74cfd0-2756-11e6-80a2-c42c9463d3b5.jpg)

i went to to see if this had change and everything under version except release went blank before my eyes. the pedal shows up as a device currently, because i powered it up with the usb attached. once i unplugged the usb and plugged it back in, it was no longer recognized. after the restart, the info screens listings for services, versions and device are all blank or unknown again.

**Comment by falkTX** [comment]
I believe I know what the issue is.
You probably loaded a big amount of effects the previous time and saved it, and now the mod is trying to load it back after booting.
The MOD should not be locking up like this, I added it as an internal bug report to fix soon.
(We'll have to leave some small percentage of the CPU free for non-audio tasks)

For now you can ssh into the mod and run:

```
rm /root/data/last.json
reboot
```

**Comment by basslayer** [comment]
is there a tutorial on ssh into this pedal using a windows machine? i am using puTTY and all i get when i use the ip address is a connection timed out error message. am i doing this wrong? for the next three days i have access to a mac as well as windows if it would be easier.

**Comment by basslayer** [comment]
i have have spent the last week trying to ssh into the pedal. every time i enter the ip address into puTTY to connect, it says "Network error: Connection timed out" and i can't enter any commands. in a new development, every time i power up the mod duo, it now goes into update mode. the right screen has the typeface logo and the left screen says "copy file, eject, and unplug" if i power it up connected to a computer and "plug USB cable to PC" if i start it without being connected to my pc.

**Comment by basslayer** [comment]
i don't know what happened but it worked itself out enough for me to connect and clear out the old pedal boards. its now working fine.
