### ISSUE TITLE
feature request: allow assign named presets to a knob

### ISSUE THREAD

**Issue by ericfont** [moddevices/mod-duo-issues#46]
For plugins which have a bunch of nice named presets (e.g. ePiano and Calf Studio Monosynth) that are selectable via the dropdown menu on their top left corner, I'd like to have a way to assign that dropdown menu to a knob.  Currently, I'm only able to assign individual parameters to a knob.

**Comment by falkTX** [comment]
this is something essential that we have in our plans for the very near future.

**Comment by falkTX** [comment]
Implemented on v0.15.0
