### ISSUE TITLE
feature request: UPDATE ALL button in gui store page

### ISSUE THREAD

**Issue by ericfont** [moddevices/mod-duo-issues#49]
I find if I want to update a bunch of my plugins, I have to do so one by one.  It would be nice to have an UPDATE ALL button so I just have to do one click.

**Comment by falkTX** [comment]
hint hint, under firefox or chrome press ctrl+shift+c to open the developer console and enter this:
`$("#cloud_update_all").click()`

**Comment by ericfont** [comment]
Wow, works nicely, thanks!  Seems that you basically have this feature underway.  :)

**Comment by falkTX** [comment]
Yeah the feature is there but needs to be implemented in the interface.

**Comment by falkTX** [comment]
'Update all' has been added in 1.0.0.
