### ISSUE TITLE
Impossible to enter precise control port value

### ISSUE THREAD

**Issue by fps** [moddevices/mod-duo-issues#5]
Using e.g. the ShiroVerb I have not found a way through the UI to set the ratio control to exactly 1.0f - using either the pedalboard controls or the detailled pedal controls. Maybe it is just non obvious though.

**Comment by falkTX** [comment]
it is a bit non-obvious yes.
open the settings for the plugin, and double-click on the text value below the knob you want to change.
those text values are editable.

**Comment by boomshop** [comment]
Will add a tiny "edit" icon later.

**Comment by fps** [comment]
OK, thanks. that makes sense. I tried double clicking the knobs themselves or opening the assignment editor ;)
