### ISSUE TITLE
Gain plugin seems broken

### ISSUE THREAD

**Issue by ytai** [moddevices/mod-duo-issues#53]
Trying to assign a MIDI controller via MIDI learn to the gain parameter of the gain 0:0.0-4 results in the value being sweeped between 0..1dB. Furthermore, the setting regarding the range of the control and the resolution of the controller does not seem to have any effect (as seems to be the case with other plugins).

**Comment by falkTX** [comment]
> Furthermore, the setting regarding the range of the control and the resolution of the controller does not seem to have any effect (as seems to be the case with other plugins).

That is correct.
Parameter ranges are not implemented yet for MIDI CC, and will be hidden from the interface when selected in the next MOD update (to prevent confusion as to why they're not being used).

Sensibility is not something that will ever work for MIDI CC though, as the value is always 127 steps.

**Comment by ytai** [comment]
Well, yeah, the resolution might not make sense, but the range does, i.e. mapping the 0..127 values to parameter space.

**Comment by falkTX** [comment]
FYI the ranges and sensibility options are hidden from >= 1.0.0.
Showing them when they're not implemented yet was confusing.

I do want to implemented them though, coming sometime soon.

**Comment by ytai** [comment]
Is anyone looking into this? I haven't found any way to have an expression pedal control the volume, which seems like a very basic requirement. Is there a reasonable workaround?

**Comment by falkTX** [comment]
Ranges for MIDI CC have been implemented in v1.2.
Have you tried it yet?

**Comment by ytai** [comment]
Seems to work fine now. Thanks!

**Comment by falkTX** [comment]
Closing this bug then.
Note that changing MIDI CC parameter ranges does not work yet in v1.3.0, but it's coming in v1.4.0.
