### ISSUE TITLE
Pedalboard loading "Bug: Couldn't load: Unauthorized"

### ISSUE THREAD

**Issue by harryhaaren** [moddevices/mod-duo-issues#55]
## Bug

Pedalboard from pedalboards.moddevices.com won't load. reason "unauthorized".
## How to reproduce
1. Boot MOD, ifconfig appeared net-dev to 192.168.51.23
2. Load mod in google-chrome (or chromium, tested both)
3. In other tab, Clicky pedalboards.moddevices.com "Try Now" button
4. Switch to MOD tab
5. Notification in top right says "Bug! Couln't load pedalboard, reason Unauthorized".

This is with the Orange MOD (was RC3 that was upgraded, Crudo registered on the day I left Berlin, Serial 0069).

Settings -> Info -> Device shows without any text, just like below. (No i didn't just forget to type it ;) :
Serial Number:
## Expected/suggested solution

Successfully load pedalboard without bug warning
## Additional information
- release: v1.0.0, 
- controller: 582516e
- system dc9b5b4
- restore 8bfd5ca
## Would you be willing or able to help resolve this issue?

( X ) Yes

**Comment by harryhaaren** [comment]
Upgraded Black (normal) MOD - works, and it has a Serial Number: XXXXXXXXXXX so that must be the issue

**Comment by harryhaaren** [comment]
Will close this - MOD DUO I was testing on was pre-release and not registered successfully.

**Comment by alercunha** [comment]
Yes Harry, you had RC3 which did not integrate properly with the auth process which is required.
