### ISSUE TITLE
Improve upgrade on-screen text

### ISSUE THREAD

**Issue by harryhaaren** [moddevices/mod-duo-issues#56]
During Upgrade step to  rename "First Footswitch" to "Left footswitch"? I think this reads better in English, and is also clearer as there is no markers on the DUO which footswitch is "Number 1"

**Comment by autostatic** [comment]
+1. I find the "first footswitch" a bit confusing, if you're used to reading from right to left then you might consider the right footswitch to be the first one. Using "Left footswitch" would take away the ambiguity.

**Comment by falkTX** [comment]
Thanks for the suggestion.
This has now been changed in 1.0.1.
