### ISSUE TITLE
Sharing Pedalboards with "Unstable" plugins

### ISSUE THREAD

**Issue by harryhaaren** [moddevices/mod-duo-issues#57]
As you know sharing of pedalboards with unstable plugins is disallowed. The problem is that the UI doesn't (easily?) show which plugins are unstable or stable.

To share a pedalboard, I have to guess which plugin is unstable, remove it, and attempt re-sharing. Bad UX here, particularly as we cannot undo the remove operation - if it didn't solve the problem, then I just threw away good work.
## Solution

In the error message "cannot share", state the name of the "offending" unstable plugin. That gives the user the information needed to remove it, and share.

**Comment by falkTX** [comment]
There's a simple solution to this - remove all your current plugins.
Since the store now only shows stable ones, you cannot go wrong. ;)

Anyway, yes, we need a label in the store for the "unstable" plugins.

**Comment by harryhaaren** [comment]
OK I'll try removing all and re-installing them then. Cheers

**Comment by falkTX** [comment]
maybe there's some javascript magic we can do here... let me see...

**Comment by harryhaaren** [comment]
Don't worry about it - its not a high priority as its only me (and others who previously installed unstable plugins). I expect your focus is users starting from v  >= 1.0.0

I'll do the workaround, no problem :)

**Comment by alercunha** [comment]
@harryhaaren as an improvement we will show on the plugin store if a plugin is marked as unstable or not.

![image](https://cloud.githubusercontent.com/assets/5490771/17259914/43c930d8-5593-11e6-82f1-48133a8dac96.png)

It's not the perfect solution since from the constructor you have no clue. But will make your life easier anyhow.

**Comment by harryhaaren** [comment]
@alercunha that looks lovely - and is a huge help - cheers guys! Feel free to close this issue (or close when the update with this change is available, whatever you like : )

**Comment by falkTX** [comment]
v1.0.3 is out now, and unstable plugins are now marked in the store.
so if you need to share pedalboards, it should be a little easier now.
