### ISSUE TITLE
USB network interface on host PC fails to autoconfigure IP adress

### ISSUE THREAD

**Issue by fps** [moddevices/mod-duo-issues#6]
Manually bringing the interface up on the host PC with ifconfig and setting its IP adress to 192.168.51.2 makes access to 192.168.51.1 (the mod) possible though.

**Comment by falkTX** [comment]
I think this depends on the network manager you use.
For me personally it auto-connects and sets up the MOD network automatically after connecting the cable.

do you use network manager, wicd or something else that handles these for you?

**Comment by fps** [comment]
I use networkmanager on ubuntu. But I live in an xmonad session and basically don't touch networkmanager at all.. By what mechanism should the autoconfiguration happen?

**Comment by falkTX** [comment]
usually the network manager GUI allows you to click & connect the MOD interface.
on some setups like yours I guess it doesn't auto-connect to new interfaces.

**Comment by fps** [comment]
Is there a DHCP server listening on the interface?

**Comment by falkTX** [comment]
yes, dnsmasq is runing inside the MOD.

**Comment by fps** [comment]
OK, yes, then it's probably just an issue of networkmanager not being configured to automatically use the interface and send a DHCP request. Thanks for the info.
