### ISSUE TITLE
Problems with system upgrade from Mac OSX

### ISSUE THREAD

**Issue by ytai** [moddevices/mod-duo-issues#60]
## Bug or Enhancement

Bug.
## Description

Tried upgrading from 0.15.0 to 1.0.3 many times, always getting stuck on "copy file, eject and unplug". This included booting directly into system upgrade mode.
Then, tried with Windows and it worked the first time.
Seems to be an issue with not detecting the USB disconnect or getting stuck in a weird state during ejection that is specific to OSX.
## How to reproduce
1. Follow the normal upgrade procedure on a Mac.
## Would you be willing or able to help resolve this issue?

(x ) Yes
( ) No

**Comment by falkTX** [comment]
This has been fixed in 1.0.1.
It's not a problem anymore anyway since we have automatic updates now.
