### ISSUE TITLE
Assignement images disappeared after update to 1.0.6

### ISSUE THREAD

**Issue by immerfroehlich** [moddevices/mod-duo-issues#66]
## Bug or Enhancement

"bug"
## Description

After an update from 1.0.5 to 1.0.6 the "assignement" images disappeared. And some knobs are not controllable from the GUI.
## How to reproduce
1. Use the update function in the lower right to update to release 1.0.6
2. Open the pedal settings
3. Try to find the assignement buttons.

System information:
- Operating system: (Linux)
- System version: (Ubuntu 16.04.1 LTS)
- Browser: Chromium 52.0.2743.116

**Comment by falkTX** [comment]
Going through the list of reported issues, I don't think this is a problem anymore in the latest v1.3.0.
Please update and confirm, thanks.

**Comment by immerfroehlich** [comment]
OK, tested it with 1.3.0.322 today and the problem does not seem to appear anymore. Great thank you very much.

**Comment by falkTX** [comment]
Thanks for confirming.
Closing this bug.
