### ISSUE TITLE
Midi Serial Out doesn't work

### ISSUE THREAD

**Issue by ericfont** [moddevices/mod-duo-issues#70]
## Bug

I can't seem to get any midi messages come out the serial midi out.  
## Description

I've tried directly connecting the midi serial in to the midi serial out to directly pass input signals to out, connected to another hardware midi synth, but that midi hardware synth won't respond.  That midi synth works fine when I'm not using mod.  I've also tried just generating a scale inside the mod and sending that mid seriali out to that hardware synth, but won't work.  So I'm pretty sure there is something going on with the mods serial out.  

Imight try inspecting the midi serial out messages when I get on my computer.

release: 1.0.6

**Comment by falkTX** [comment]
There was a related issue we found recently. Fixed in 1.1.0-RC2.
Serial-out event queue was wrong.

Can you try that please?

**Comment by ericfont** [comment]
1.1.0-RC2 worked, thanks!
