### ISSUE TITLE
ModDevices uses bad phishing/tracking techniques in email links

### ISSUE THREAD

**Issue by fps** [moddevices/mod-duo-issues#71]
Now fill in these sections below:
## Bug or Enhancement

Bug
## Description

<pre>

7:12 < fps_> i think i mentioned it before
07:12 < fps_> the links to surveys you post do weird things.
07:12 < fps_> in emails they looks like this:
07:12 < fps_> : https://moddevices.typeform.com/to/ylJBnA
07:12 < fps_> which already looks suspiciously like phishing
07:12 < fps_> but then the real link goes to
07:13 < fps_> http://moddevices.us7.list-manage.com/track/click?u=c861447ed0c3cb86f66679005&id=bc1ee2e0ce&e=c3c298cc24
07:13 < fps_> which is the worst of the worst in tracking, deceiption, etc
07:13 < fps_> i won't take part in surveys that use this kind of tech anymore
07:13 -!- You're now known as fps
07:14 < fps> and even thunderbird warns me directly "Thunderbird thinks this message may be scam"
07:15 < fps> i'm not angry about it, but a little bit irritated about the ignorance displayed by using these kinds of survey platforms

</pre>

## How to reproduce

Receive emails
## Expected/suggested solution

Do the right thing
## Additional information
- Operating system: (Linux, Mac or Windows)

This issue is truly cross platform
- System version: (Windows 10 or Mac 10.10, etc)

This issue is truly cross version

**Comment by alercunha** [comment]
Thanks for reporting this, we'll look into that issue in future surveys. I'll have to close this issue though as it's not related to mod-duo directly.
