### ISSUE TITLE
enhancement: mod-ui display full string of usb midi devices when hover mouse over in/out

### ISSUE THREAD

**Issue by ericfont** [moddevices/mod-duo-issues#73]
## Enhancement

When hovering the mouse on top of any of the USB midi inputs or any of the USB midi outputs, then the full string of the USB midi device should be displayed, not just the first word of the string.
## Description

Take a look at the _full_ string names in my midi ports list here:
![midi-ports-list-but-no-checkboxes](https://cloud.githubusercontent.com/assets/6502474/18981680/a83c1610-86ae-11e6-9056-e10eca22cfc8.png)

But notice that when I hover my mosue over an input, it just shows the first word, so "EWI USB MIDI 1" becomes "Hardware EWI", while "USB Keystation 49e MIDI 1" becomes "Hardware USB":

![hardware ewi](https://cloud.githubusercontent.com/assets/6502474/18981668/8dcf274a-86ae-11e6-8d52-a7ac04d7363b.png)

![hardware usb](https://cloud.githubusercontent.com/assets/6502474/18981670/8f9050a4-86ae-11e6-9cb0-6eaa2090ea6f.png)

These shorted strings can be confusing.  In my case I wouldn't know which device "Hardware USB" refers to without using my memory.
## Expected/suggested solution

full string names when mouse over, please.
## Additional information

---
- version: 1.1.0-RC2
- controller: d8d8f0e

labtop is x86-64 Arch linux chromium browser.

**Comment by ericfont** [comment]
I should also say for expected/suggested solution that the word "In" or "Out" should also always appear at the end of the full name of each midi device.

**Comment by falkTX** [comment]
This has been fixed in v1.3.0.

**Comment by ericfont** [comment]
Thanks falk!
