### ISSUE TITLE
sooperlooper: undo after first recording breaks sooperlooper until reset button pressed

### ISSUE THREAD

**Issue by fps** [moddevices/mod-duo-issues#8]
1. enable play 
2. record a loop and stop recording
3. the loop now plays
4. undo the recording
5. record a new loop and stop recording
6. the new loop does not play
7. go back to 4.

Note: this only happens with the first recorded loop. Additional loops (recorded over a first playing one) can be undone just fine.

Resetting the SL reenables recording of the first loop

**Comment by odurc** [comment]
Thanks for reporting. Bug solved and available to update via plugin store.
