### ISSUE TITLE
Favorite count is not updated when filtering

### ISSUE THREAD

**Issue by x42** [moddevices/mod-duo-issues#86]
## Description

Plugins by keywords.    plugins that don't match are hidden from the "Favorites"  but the number is not updated.  it still says "Favorites (NN)"

## How to reproduce

 1. Add some plugins to the favorites
 2. Search/filter the plugin list
 
## Expected/suggested solution

When no favorites match the keywords the tab header says "Favorites (0)"

---

* release: 1.2.0.240-RC2

**Comment by falkTX** [comment]
Fixed in https://github.com/moddevices/mod-ui/commit/24a5613d1b7ad8863cfc22042a8467bc8c7a6ac0
Will be available in the next 1.2-rc update
