### ISSUE TITLE
Enhancement: Headphone out mono

### ISSUE THREAD

**Issue by mitchmarkerink** [moddevices/mod-duo-issues#90]
Hi team mod duo,

Is it possible to map the audio out signal in the web interface as well. I would like to map output 1 or 2 to the headphone out jack. I us the mod duo as two mono effects chain with the loops from my Source Audio Kingmaker fuzz in between. 
![mod duo](https://user-images.githubusercontent.com/31122108/29445907-89d9339a-83e9-11e7-9e6e-0ec007d61b86.png)

**Comment by odurc** [comment]
Unfortunately that's not possible. The headphones always output the input 1 and input 2. Check this topic for more details: https://forum.moddevices.com/t/headphone-jack-as-additional-output/1020
